/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthTransactionsRouteImport } from './routes/_auth/transactions'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthReportsIndexRouteImport } from './routes/_auth/reports/index'
import { Route as AuthProductsIndexRouteImport } from './routes/_auth/products/index'
import { Route as AuthLoansIndexRouteImport } from './routes/_auth/loans/index'
import { Route as AuthCooperativeIndexRouteImport } from './routes/_auth/cooperative/index'
import { Route as AuthClientsIndexRouteImport } from './routes/_auth/clients/index'
import { Route as AuthAdministrationIndexRouteImport } from './routes/_auth/administration/index'
import { Route as AuthProductsSharesRouteImport } from './routes/_auth/products/shares'
import { Route as AuthProductsSavingsRouteImport } from './routes/_auth/products/savings'
import { Route as AuthProductsPrepaidRouteImport } from './routes/_auth/products/prepaid'
import { Route as AuthProductsLoansRouteImport } from './routes/_auth/products/loans'
import { Route as AuthLoansRepaymentsRouteImport } from './routes/_auth/loans/repayments'
import { Route as AuthLoansProductsRouteImport } from './routes/_auth/loans/products'
import { Route as AuthLoansDisbursementsRouteImport } from './routes/_auth/loans/disbursements'
import { Route as AuthLoansCollateralRouteImport } from './routes/_auth/loans/collateral'
import { Route as AuthLoansArrearsRouteImport } from './routes/_auth/loans/arrears'
import { Route as AuthLoansApprovalsRouteImport } from './routes/_auth/loans/approvals'
import { Route as AuthLoansApplicationsRouteImport } from './routes/_auth/loans/applications'
import { Route as AuthLoansActiveRouteImport } from './routes/_auth/loans/active'
import { Route as AuthLoansLoanIdRouteImport } from './routes/_auth/loans/$loanId'
import { Route as AuthCooperativeMembershipRouteImport } from './routes/_auth/cooperative/membership'
import { Route as AuthCooperativeGovernanceRouteImport } from './routes/_auth/cooperative/governance'
import { Route as AuthCooperativeConfigurationsRouteImport } from './routes/_auth/cooperative/configurations'
import { Route as AuthClientsAddRouteImport } from './routes/_auth/clients/add'
import { Route as AuthClientsAccountLookupRouteImport } from './routes/_auth/clients/account-lookup'
import { Route as AuthClientsClientIdRouteImport } from './routes/_auth/clients/$clientId'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTransactionsRoute = AuthTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReportsIndexRoute = AuthReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProductsIndexRoute = AuthProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoansIndexRoute = AuthLoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCooperativeIndexRoute = AuthCooperativeIndexRouteImport.update({
  id: '/cooperative/',
  path: '/cooperative/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClientsIndexRoute = AuthClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdministrationIndexRoute = AuthAdministrationIndexRouteImport.update({
  id: '/administration/',
  path: '/administration/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProductsSharesRoute = AuthProductsSharesRouteImport.update({
  id: '/products/shares',
  path: '/products/shares',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProductsSavingsRoute = AuthProductsSavingsRouteImport.update({
  id: '/products/savings',
  path: '/products/savings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProductsPrepaidRoute = AuthProductsPrepaidRouteImport.update({
  id: '/products/prepaid',
  path: '/products/prepaid',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProductsLoansRoute = AuthProductsLoansRouteImport.update({
  id: '/products/loans',
  path: '/products/loans',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoansRepaymentsRoute = AuthLoansRepaymentsRouteImport.update({
  id: '/loans/repayments',
  path: '/loans/repayments',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoansProductsRoute = AuthLoansProductsRouteImport.update({
  id: '/loans/products',
  path: '/loans/products',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoansDisbursementsRoute = AuthLoansDisbursementsRouteImport.update({
  id: '/loans/disbursements',
  path: '/loans/disbursements',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoansCollateralRoute = AuthLoansCollateralRouteImport.update({
  id: '/loans/collateral',
  path: '/loans/collateral',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoansArrearsRoute = AuthLoansArrearsRouteImport.update({
  id: '/loans/arrears',
  path: '/loans/arrears',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoansApprovalsRoute = AuthLoansApprovalsRouteImport.update({
  id: '/loans/approvals',
  path: '/loans/approvals',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoansApplicationsRoute = AuthLoansApplicationsRouteImport.update({
  id: '/loans/applications',
  path: '/loans/applications',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoansActiveRoute = AuthLoansActiveRouteImport.update({
  id: '/loans/active',
  path: '/loans/active',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoansLoanIdRoute = AuthLoansLoanIdRouteImport.update({
  id: '/loans/$loanId',
  path: '/loans/$loanId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCooperativeMembershipRoute =
  AuthCooperativeMembershipRouteImport.update({
    id: '/cooperative/membership',
    path: '/cooperative/membership',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthCooperativeGovernanceRoute =
  AuthCooperativeGovernanceRouteImport.update({
    id: '/cooperative/governance',
    path: '/cooperative/governance',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthCooperativeConfigurationsRoute =
  AuthCooperativeConfigurationsRouteImport.update({
    id: '/cooperative/configurations',
    path: '/cooperative/configurations',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthClientsAddRoute = AuthClientsAddRouteImport.update({
  id: '/clients/add',
  path: '/clients/add',
  getParentRoute: () => AuthRoute,
} as any)
const AuthClientsAccountLookupRoute =
  AuthClientsAccountLookupRouteImport.update({
    id: '/clients/account-lookup',
    path: '/clients/account-lookup',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthClientsClientIdRoute = AuthClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/signin': typeof SigninRoute
  '/dashboard': typeof AuthDashboardRoute
  '/transactions': typeof AuthTransactionsRoute
  '/clients/$clientId': typeof AuthClientsClientIdRoute
  '/clients/account-lookup': typeof AuthClientsAccountLookupRoute
  '/clients/add': typeof AuthClientsAddRoute
  '/cooperative/configurations': typeof AuthCooperativeConfigurationsRoute
  '/cooperative/governance': typeof AuthCooperativeGovernanceRoute
  '/cooperative/membership': typeof AuthCooperativeMembershipRoute
  '/loans/$loanId': typeof AuthLoansLoanIdRoute
  '/loans/active': typeof AuthLoansActiveRoute
  '/loans/applications': typeof AuthLoansApplicationsRoute
  '/loans/approvals': typeof AuthLoansApprovalsRoute
  '/loans/arrears': typeof AuthLoansArrearsRoute
  '/loans/collateral': typeof AuthLoansCollateralRoute
  '/loans/disbursements': typeof AuthLoansDisbursementsRoute
  '/loans/products': typeof AuthLoansProductsRoute
  '/loans/repayments': typeof AuthLoansRepaymentsRoute
  '/products/loans': typeof AuthProductsLoansRoute
  '/products/prepaid': typeof AuthProductsPrepaidRoute
  '/products/savings': typeof AuthProductsSavingsRoute
  '/products/shares': typeof AuthProductsSharesRoute
  '/administration/': typeof AuthAdministrationIndexRoute
  '/clients/': typeof AuthClientsIndexRoute
  '/cooperative/': typeof AuthCooperativeIndexRoute
  '/loans/': typeof AuthLoansIndexRoute
  '/products/': typeof AuthProductsIndexRoute
  '/reports/': typeof AuthReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/signin': typeof SigninRoute
  '/dashboard': typeof AuthDashboardRoute
  '/transactions': typeof AuthTransactionsRoute
  '/clients/$clientId': typeof AuthClientsClientIdRoute
  '/clients/account-lookup': typeof AuthClientsAccountLookupRoute
  '/clients/add': typeof AuthClientsAddRoute
  '/cooperative/configurations': typeof AuthCooperativeConfigurationsRoute
  '/cooperative/governance': typeof AuthCooperativeGovernanceRoute
  '/cooperative/membership': typeof AuthCooperativeMembershipRoute
  '/loans/$loanId': typeof AuthLoansLoanIdRoute
  '/loans/active': typeof AuthLoansActiveRoute
  '/loans/applications': typeof AuthLoansApplicationsRoute
  '/loans/approvals': typeof AuthLoansApprovalsRoute
  '/loans/arrears': typeof AuthLoansArrearsRoute
  '/loans/collateral': typeof AuthLoansCollateralRoute
  '/loans/disbursements': typeof AuthLoansDisbursementsRoute
  '/loans/products': typeof AuthLoansProductsRoute
  '/loans/repayments': typeof AuthLoansRepaymentsRoute
  '/products/loans': typeof AuthProductsLoansRoute
  '/products/prepaid': typeof AuthProductsPrepaidRoute
  '/products/savings': typeof AuthProductsSavingsRoute
  '/products/shares': typeof AuthProductsSharesRoute
  '/administration': typeof AuthAdministrationIndexRoute
  '/clients': typeof AuthClientsIndexRoute
  '/cooperative': typeof AuthCooperativeIndexRoute
  '/loans': typeof AuthLoansIndexRoute
  '/products': typeof AuthProductsIndexRoute
  '/reports': typeof AuthReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/signin': typeof SigninRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/transactions': typeof AuthTransactionsRoute
  '/_auth/clients/$clientId': typeof AuthClientsClientIdRoute
  '/_auth/clients/account-lookup': typeof AuthClientsAccountLookupRoute
  '/_auth/clients/add': typeof AuthClientsAddRoute
  '/_auth/cooperative/configurations': typeof AuthCooperativeConfigurationsRoute
  '/_auth/cooperative/governance': typeof AuthCooperativeGovernanceRoute
  '/_auth/cooperative/membership': typeof AuthCooperativeMembershipRoute
  '/_auth/loans/$loanId': typeof AuthLoansLoanIdRoute
  '/_auth/loans/active': typeof AuthLoansActiveRoute
  '/_auth/loans/applications': typeof AuthLoansApplicationsRoute
  '/_auth/loans/approvals': typeof AuthLoansApprovalsRoute
  '/_auth/loans/arrears': typeof AuthLoansArrearsRoute
  '/_auth/loans/collateral': typeof AuthLoansCollateralRoute
  '/_auth/loans/disbursements': typeof AuthLoansDisbursementsRoute
  '/_auth/loans/products': typeof AuthLoansProductsRoute
  '/_auth/loans/repayments': typeof AuthLoansRepaymentsRoute
  '/_auth/products/loans': typeof AuthProductsLoansRoute
  '/_auth/products/prepaid': typeof AuthProductsPrepaidRoute
  '/_auth/products/savings': typeof AuthProductsSavingsRoute
  '/_auth/products/shares': typeof AuthProductsSharesRoute
  '/_auth/administration/': typeof AuthAdministrationIndexRoute
  '/_auth/clients/': typeof AuthClientsIndexRoute
  '/_auth/cooperative/': typeof AuthCooperativeIndexRoute
  '/_auth/loans/': typeof AuthLoansIndexRoute
  '/_auth/products/': typeof AuthProductsIndexRoute
  '/_auth/reports/': typeof AuthReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/signin'
    | '/dashboard'
    | '/transactions'
    | '/clients/$clientId'
    | '/clients/account-lookup'
    | '/clients/add'
    | '/cooperative/configurations'
    | '/cooperative/governance'
    | '/cooperative/membership'
    | '/loans/$loanId'
    | '/loans/active'
    | '/loans/applications'
    | '/loans/approvals'
    | '/loans/arrears'
    | '/loans/collateral'
    | '/loans/disbursements'
    | '/loans/products'
    | '/loans/repayments'
    | '/products/loans'
    | '/products/prepaid'
    | '/products/savings'
    | '/products/shares'
    | '/administration/'
    | '/clients/'
    | '/cooperative/'
    | '/loans/'
    | '/products/'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/signin'
    | '/dashboard'
    | '/transactions'
    | '/clients/$clientId'
    | '/clients/account-lookup'
    | '/clients/add'
    | '/cooperative/configurations'
    | '/cooperative/governance'
    | '/cooperative/membership'
    | '/loans/$loanId'
    | '/loans/active'
    | '/loans/applications'
    | '/loans/approvals'
    | '/loans/arrears'
    | '/loans/collateral'
    | '/loans/disbursements'
    | '/loans/products'
    | '/loans/repayments'
    | '/products/loans'
    | '/products/prepaid'
    | '/products/savings'
    | '/products/shares'
    | '/administration'
    | '/clients'
    | '/cooperative'
    | '/loans'
    | '/products'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/forgot-password'
    | '/signin'
    | '/_auth/dashboard'
    | '/_auth/transactions'
    | '/_auth/clients/$clientId'
    | '/_auth/clients/account-lookup'
    | '/_auth/clients/add'
    | '/_auth/cooperative/configurations'
    | '/_auth/cooperative/governance'
    | '/_auth/cooperative/membership'
    | '/_auth/loans/$loanId'
    | '/_auth/loans/active'
    | '/_auth/loans/applications'
    | '/_auth/loans/approvals'
    | '/_auth/loans/arrears'
    | '/_auth/loans/collateral'
    | '/_auth/loans/disbursements'
    | '/_auth/loans/products'
    | '/_auth/loans/repayments'
    | '/_auth/products/loans'
    | '/_auth/products/prepaid'
    | '/_auth/products/savings'
    | '/_auth/products/shares'
    | '/_auth/administration/'
    | '/_auth/clients/'
    | '/_auth/cooperative/'
    | '/_auth/loans/'
    | '/_auth/products/'
    | '/_auth/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/transactions': {
      id: '/_auth/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthTransactionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reports/': {
      id: '/_auth/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthReportsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products/': {
      id: '/_auth/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthProductsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/loans/': {
      id: '/_auth/loans/'
      path: '/loans'
      fullPath: '/loans/'
      preLoaderRoute: typeof AuthLoansIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cooperative/': {
      id: '/_auth/cooperative/'
      path: '/cooperative'
      fullPath: '/cooperative/'
      preLoaderRoute: typeof AuthCooperativeIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/clients/': {
      id: '/_auth/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthClientsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/administration/': {
      id: '/_auth/administration/'
      path: '/administration'
      fullPath: '/administration/'
      preLoaderRoute: typeof AuthAdministrationIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products/shares': {
      id: '/_auth/products/shares'
      path: '/products/shares'
      fullPath: '/products/shares'
      preLoaderRoute: typeof AuthProductsSharesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products/savings': {
      id: '/_auth/products/savings'
      path: '/products/savings'
      fullPath: '/products/savings'
      preLoaderRoute: typeof AuthProductsSavingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products/prepaid': {
      id: '/_auth/products/prepaid'
      path: '/products/prepaid'
      fullPath: '/products/prepaid'
      preLoaderRoute: typeof AuthProductsPrepaidRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products/loans': {
      id: '/_auth/products/loans'
      path: '/products/loans'
      fullPath: '/products/loans'
      preLoaderRoute: typeof AuthProductsLoansRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/loans/repayments': {
      id: '/_auth/loans/repayments'
      path: '/loans/repayments'
      fullPath: '/loans/repayments'
      preLoaderRoute: typeof AuthLoansRepaymentsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/loans/products': {
      id: '/_auth/loans/products'
      path: '/loans/products'
      fullPath: '/loans/products'
      preLoaderRoute: typeof AuthLoansProductsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/loans/disbursements': {
      id: '/_auth/loans/disbursements'
      path: '/loans/disbursements'
      fullPath: '/loans/disbursements'
      preLoaderRoute: typeof AuthLoansDisbursementsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/loans/collateral': {
      id: '/_auth/loans/collateral'
      path: '/loans/collateral'
      fullPath: '/loans/collateral'
      preLoaderRoute: typeof AuthLoansCollateralRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/loans/arrears': {
      id: '/_auth/loans/arrears'
      path: '/loans/arrears'
      fullPath: '/loans/arrears'
      preLoaderRoute: typeof AuthLoansArrearsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/loans/approvals': {
      id: '/_auth/loans/approvals'
      path: '/loans/approvals'
      fullPath: '/loans/approvals'
      preLoaderRoute: typeof AuthLoansApprovalsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/loans/applications': {
      id: '/_auth/loans/applications'
      path: '/loans/applications'
      fullPath: '/loans/applications'
      preLoaderRoute: typeof AuthLoansApplicationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/loans/active': {
      id: '/_auth/loans/active'
      path: '/loans/active'
      fullPath: '/loans/active'
      preLoaderRoute: typeof AuthLoansActiveRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/loans/$loanId': {
      id: '/_auth/loans/$loanId'
      path: '/loans/$loanId'
      fullPath: '/loans/$loanId'
      preLoaderRoute: typeof AuthLoansLoanIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cooperative/membership': {
      id: '/_auth/cooperative/membership'
      path: '/cooperative/membership'
      fullPath: '/cooperative/membership'
      preLoaderRoute: typeof AuthCooperativeMembershipRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cooperative/governance': {
      id: '/_auth/cooperative/governance'
      path: '/cooperative/governance'
      fullPath: '/cooperative/governance'
      preLoaderRoute: typeof AuthCooperativeGovernanceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cooperative/configurations': {
      id: '/_auth/cooperative/configurations'
      path: '/cooperative/configurations'
      fullPath: '/cooperative/configurations'
      preLoaderRoute: typeof AuthCooperativeConfigurationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/clients/add': {
      id: '/_auth/clients/add'
      path: '/clients/add'
      fullPath: '/clients/add'
      preLoaderRoute: typeof AuthClientsAddRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/clients/account-lookup': {
      id: '/_auth/clients/account-lookup'
      path: '/clients/account-lookup'
      fullPath: '/clients/account-lookup'
      preLoaderRoute: typeof AuthClientsAccountLookupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/clients/$clientId': {
      id: '/_auth/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthClientsClientIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthTransactionsRoute: typeof AuthTransactionsRoute
  AuthClientsClientIdRoute: typeof AuthClientsClientIdRoute
  AuthClientsAccountLookupRoute: typeof AuthClientsAccountLookupRoute
  AuthClientsAddRoute: typeof AuthClientsAddRoute
  AuthCooperativeConfigurationsRoute: typeof AuthCooperativeConfigurationsRoute
  AuthCooperativeGovernanceRoute: typeof AuthCooperativeGovernanceRoute
  AuthCooperativeMembershipRoute: typeof AuthCooperativeMembershipRoute
  AuthLoansLoanIdRoute: typeof AuthLoansLoanIdRoute
  AuthLoansActiveRoute: typeof AuthLoansActiveRoute
  AuthLoansApplicationsRoute: typeof AuthLoansApplicationsRoute
  AuthLoansApprovalsRoute: typeof AuthLoansApprovalsRoute
  AuthLoansArrearsRoute: typeof AuthLoansArrearsRoute
  AuthLoansCollateralRoute: typeof AuthLoansCollateralRoute
  AuthLoansDisbursementsRoute: typeof AuthLoansDisbursementsRoute
  AuthLoansProductsRoute: typeof AuthLoansProductsRoute
  AuthLoansRepaymentsRoute: typeof AuthLoansRepaymentsRoute
  AuthProductsLoansRoute: typeof AuthProductsLoansRoute
  AuthProductsPrepaidRoute: typeof AuthProductsPrepaidRoute
  AuthProductsSavingsRoute: typeof AuthProductsSavingsRoute
  AuthProductsSharesRoute: typeof AuthProductsSharesRoute
  AuthAdministrationIndexRoute: typeof AuthAdministrationIndexRoute
  AuthClientsIndexRoute: typeof AuthClientsIndexRoute
  AuthCooperativeIndexRoute: typeof AuthCooperativeIndexRoute
  AuthLoansIndexRoute: typeof AuthLoansIndexRoute
  AuthProductsIndexRoute: typeof AuthProductsIndexRoute
  AuthReportsIndexRoute: typeof AuthReportsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthTransactionsRoute: AuthTransactionsRoute,
  AuthClientsClientIdRoute: AuthClientsClientIdRoute,
  AuthClientsAccountLookupRoute: AuthClientsAccountLookupRoute,
  AuthClientsAddRoute: AuthClientsAddRoute,
  AuthCooperativeConfigurationsRoute: AuthCooperativeConfigurationsRoute,
  AuthCooperativeGovernanceRoute: AuthCooperativeGovernanceRoute,
  AuthCooperativeMembershipRoute: AuthCooperativeMembershipRoute,
  AuthLoansLoanIdRoute: AuthLoansLoanIdRoute,
  AuthLoansActiveRoute: AuthLoansActiveRoute,
  AuthLoansApplicationsRoute: AuthLoansApplicationsRoute,
  AuthLoansApprovalsRoute: AuthLoansApprovalsRoute,
  AuthLoansArrearsRoute: AuthLoansArrearsRoute,
  AuthLoansCollateralRoute: AuthLoansCollateralRoute,
  AuthLoansDisbursementsRoute: AuthLoansDisbursementsRoute,
  AuthLoansProductsRoute: AuthLoansProductsRoute,
  AuthLoansRepaymentsRoute: AuthLoansRepaymentsRoute,
  AuthProductsLoansRoute: AuthProductsLoansRoute,
  AuthProductsPrepaidRoute: AuthProductsPrepaidRoute,
  AuthProductsSavingsRoute: AuthProductsSavingsRoute,
  AuthProductsSharesRoute: AuthProductsSharesRoute,
  AuthAdministrationIndexRoute: AuthAdministrationIndexRoute,
  AuthClientsIndexRoute: AuthClientsIndexRoute,
  AuthCooperativeIndexRoute: AuthCooperativeIndexRoute,
  AuthLoansIndexRoute: AuthLoansIndexRoute,
  AuthProductsIndexRoute: AuthProductsIndexRoute,
  AuthReportsIndexRoute: AuthReportsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
